### ISSUE TITLE
Crash with URL-safe Base64 tokens

### ISSUE THREAD

**Issue by vocoded** [zelloptt/zello-ios-sdk#8]
When calling session.connect with a URL-safe Base64 token like so:

```
    session = [[ZCCSession alloc] initWithURL:url authToken:authToken username:username password:password channel:channel callbackQueue:nil];
    session.delegate = self;
    [session connect];
```

The application terminates with an exception:

```
2020-10-29 12:50:37.358739+1100 mesh[905:276134] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
```

The relevant code is in a dev token checking block here:

https://github.com/zelloptt/zello-ios-sdk/blob/4eeeaef8f0283825f1cf6e1ded0b6f1c70426ed5/ZelloChannelKit/ZelloChannelKit/ZCCSession.m#L37

**Comment by cooksey** [comment]
@vocoded Please attach a token that causes this crash. I ran into something similar a while back and it's because the two sides were making different assumptions about how base64 encoding should work.
